#!/bin/bash

# Check if an IP address is provided as an argument
if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Store the provided IP address in a variable
IP_ADDRESS=$1

# Ping the provided IP address 5 times
ping -c 5 "$IP_ADDRESS"
