#!/usr/bin/env bash
# Command to ping an IP address passed as an argument

# Check if the number of arguments is equal to 0
if [ $# -eq 0 ]; then
    # If no argument is provided, display an error message
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    # Ping the provided IP address 5 times
    ping -c 5 "$1"
fi
